### ISSUE TITLE
default font with serif

### ISSUE THREAD

**Issue by lelutin** [nomeata/screen-message#2]
Hi there!

screen-message is really useful in a lot of contexts. However I'm wondering why the default font chosen was "sans-serif"?

Reading on-screen is a lot easier with serif fonts so I'd suggest to change the default fontspect to "serif".

**Comment by SolidTux** [comment]
Serif fonts are used for running texts as they provide helping "lines" to help you keep in that line. But for headers, presentations etc. normally a sans-serif font is used as it's "clearer". So (at least for me) it's more logical to use a sans-serif font for a short text.

Quoting from [here](https://www.fonts.com/content/learning/fontology/level-1/type-anatomy/serif-vs-sans-for-text-in-print):

> For projects involving lengthy text, such as books, newspapers, and most magazines, serif typefaces are the most commonly used typestyle. Their prevalence stems from a combination of historical precedent and perceived readability. On the other hand, sans serif text typefaces can be used for annual reports and brochures. Sans serifs can also work well for magazines and other materials that allow for a more liberal design approach.
>
>For other shorter text settings – such as captions, credits, column headings, as well as text in charts and graphs – a sans serif typeface can be a good choice. Its simplified letterforms are unencumbered by serifs, which can impede the readability of characters at very small sizes.

**Comment by nomeata** [comment]
This is clearly a matter of choice… and I made this one. You probably know that, but for the record: You can use `sm --font=serif` to have serif fonts

**Comment by lelutin** [comment]
well fair enough. I had to try :)
