### ISSUE TITLE
[Feature request] Choose the display used

### ISSUE THREAD

**Issue by blackICE19240** [nomeata/screen-message#20]
I was wondering if you could add the ability to choose the display the message is shown on?

I would like to be able to trigger a screen message on a device I am connected to through SSH, but i get this error `(sm:1091950): Gtk-WARNING **: 13:30:46.306: cannot open display: ` I assume this is because it's not trying to use the machine's actual display and I imagine being able to choose the display manually would solve this. Running the same command locally works properly btw

**Comment by nomeata** [comment]
Do other gtk-based applications work in that setting?

I assume you are facing the more general question of setting the `DISPLAY` variable, which then `screen-message` will use if set correctly.

**Comment by blackICE19240** [comment]
I actually already tried this but apparently I did something wrong last time.
**Thank you.**

If anyone else happens to have this 'problem', in SSH, I just ran `export DISPLAY=:0` first and then it works as desired.
