### ISSUE TITLE
Git tags for releases?

### ISSUE THREAD

**Issue by hartwork** [nomeata/screen-message#3]
Hi!

I would like to watch screen-message for new releases using https://github.com/vfeskov/WinABeer so that I can keep the Gentoo package up to date with minimal delay but it would take Git tags for releases to be able to do that. Any chance you could add Git tags for releases? I'd be happy to help reconstruct tags for older releases if wanted.

Best, Sebastian

**Comment by hartwork** [comment]
@nomeata any thoughts?

**Comment by nomeata** [comment]
I had a bunch of tags already, but it seems they did not migrate to github yet. Fixed: https://github.com/nomeata/screen-message/tags

Also tried to tag 0.26 retroactively to what it probably was.

**Comment by nomeata** [comment]
I’m closing this, hoping to remember to tag and push when and if I do a new release.

**Comment by hartwork** [comment]
@nomeata thank you! :+1:
