### ISSUE TITLE
windowed mode

### ISSUE THREAD

**Issue by korakinos** [nomeata/screen-message#7]
I think a windowed (i.e. non-fullscreen) mode could be useful for live presentations where I want to show something else beside live-typed text.

I found that the code change to disable fullscreen is extremely simple: Just comment the line 
`gtk_window_fullscreen(GTK_WINDOW(window));`
in sm.c. 

I don't know how involved it would be to have windowed mode togglable by a shortcut or a command line switch, and I understand if you don't want to make the change in order to keep screen-message simple. (I can use my locally compiled windowed version for the time being.)

**Comment by hartwork** [comment]
I have a similar use case where I want half the screen to be a big countdown clock (five minutes to zero) and screen-message would work well for that if I could just put it in windowed mode :+1: I found now that with `wmctrl -r sm -b remove,fullscreen` it is already possible to put sm into windowed mode. Maybe it works well for others too.

**Comment by nomeata** [comment]
Maybe I never worried because with my window manager (XMonad), I can just resize the full-screen window, and place it where it needs to be.

@hartwork’s suggestion is a good work-around though, although I’m not opposed to a command line flag for a windowed mode.

**Comment by korakinos** [comment]
> Maybe I never worried because with my window manager (XMonad), I can just resize the full-screen window, and place it where it needs to be.

Of course! I only guess that whatever I was using four years ago didn't make this possible, but now (with i3), this is not a problem for me anymore. As far as I am concerned, you can close this issue; or leave it open in case anyone wants to implement the feature.

**Comment by nomeata** [comment]
Yay, I can close an issue! :-)
